# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Download gomod-cap tool
      run: go install github.com/gotify/plugin-api/cmd/gomod-cap@latest

    - name: Get Gotify server Go version
      run: make get-gotify-server-go-version

    - name: Update Go modules
      run: make update-go-mod
      
    - name: Build plugin
      run: make GOTIFY_VERSION="v2.5.0" build

    - name: Archive build outputs
      uses: actions/upload-artifact@v3
      with:
        name: plugin-artifacts
        path: ./build
