# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.1'

    - name: Download gomod-cap tool
      run: go install github.com/gotify/plugin-api/cmd/gomod-cap@latest
      
    - name: Build plugin
      run: make GOTIFY_VERSION="v2.7.2" build

    - name: Archive build outputs
      uses: actions/upload-artifact@v4
      with:
        name: plugin-artifacts
        path: ./build
